development:
  adapter: async

test:
  adapter: test

production:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
  url: <%= ENV["REDIS_URL"] || "redis://localhost:6379/1" %>
