default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: navigation_app_development
  username: postgres
  password: your_password_here
  host: localhost

test:
  <<: *default
  database: navigation_app_test
  username: postgres
  password: your_password_here
  host: localhost

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>


cable:
  production:
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>

