default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: dpg-d3b2linfte5s739dppl0-a.oregon-postgres.render.com
  username: navigation_app_production_user
  password: qGfbutxk8tA2r90oJOxBNNCa2V6ghfLg

development:
  <<: *default
  database: navigation_app_development

test:
  <<: *default
  database: navigation_app_test

production:
  <<: *default
  database: navigation_app_production

queue:
  <<: *default
  database: navigation_app_production
