default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: navigation_app_development
  username: postgres
  password: your_password_here
  host: localhost

test:
  <<: *default
  database: navigation_app_test
  username: postgres
  password: your_password_here
  host: localhost

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

cable:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

  queue:
  <<: *production
  database: navigation_app_development